export const CONTENT = `class C_NPC {
    var int ID;
    var int NAME;
    var int SLOT;
    var int NPCTYPE;
    var int FLAGS;
    var int ATTRIBUTE;
    var int PROTECTION;
    var int DAMAGE;
    var int DAMAGETYPE;
    var int GUILD;
    var int LEVEL;
    var int MISSION;
    var int FIGHT_TACTIC;
    var int WEAPON;
    var int VOICE;
    var int VOICEPITCH;
    var int BODYMASS;
    var int DAILY_ROUTINE;
    var int START_AISTATE;
    var int SPAWNPOINT;
    var int SPAWNDELAY;
    var int SENSES;
    var int SENSES_RANGE;
    var int AIVAR;
    var int WP;
    var int EXP;
    var int EXP_NEXT;
    var int LP;
    var int HITCHANCE;
    var int BODYSTATEINTERRUPTABLEOVERRIDE;
    var int NOFOCUS;
    var int EFFECT;
};
class C_ITEM {
    var int ID;
    var int NAME;
    var int NAMEID;
    var int HP;
    var int HP_MAX;
    var int MAINFLAG;
    var int FLAGS;
    var int WEIGHT;
    var int VALUE;
    var int DAMAGETYPE;
    var int DAMAGETOTAL;
    var int DAMAGE;
    var int WEAR;
    var int PROTECTION;
    var int NUTRITION;
    var int COND_ATR;
    var int COND_VALUE;
    var int CHANGE_ATR;
    var int CHANGE_VALUE;
    var int MAGIC;
    var int ON_EQUIP;
    var int ON_UNEQUIP;
    var int ON_STATE;
    var int OWNER;
    var int OWNERGUILD;
    var int DISGUISEGUILD;
    var int VISUAL;
    var int VISUAL_CHANGE;
    var int VISUAL_SKIN;
    var int SCEMENAME;
    var int MATERIAL;
    var int MUNITION;
    var int SPELL;
    var int RANGE;
    var int MAG_CIRCLE;
    var int DESCRIPTION;
    var int TEXT;
    var int COUNT;
    var int INV_ZBIAS;
    var int INV_ROTX;
    var int INV_ROTY;
    var int INV_ROTZ;
    var int INV_ANIMATE;
    var int EFFECT;
};
instance SELF(C_NPC);
instance OTHER(C_NPC);
instance VICTIM(C_NPC);
instance HERO(C_NPC);
instance ITEM(C_ITEM);
func void STARTUP_GLOBAL() {};
func void INIT_GLOBAL() {};
`
